# Generated by Django 3.0.8 on 2020-08-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('account_number', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=50)),
                ('account_balance', models.CharField(max_length=100)),
            ],
        ),
    ]
