# Generated by Django 3.0.8 on 2020-08-15 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0002_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Contact',
        ),
    ]
