# Generated by Django 3.0.8 on 2020-08-17 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0004_remove_bank_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='email',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='name',
        ),
    ]
